services:
  app:
    image: kmenovschikov/em_test:app-1.0
    container_name: backend
    networks:
      mynet:
        ipv4_address: 192.168.168.2
  web:
    image: kmenovschikov/em_test:nginx-1.0
    container_name: nginx
    ports:
      - 80:80
    networks:
      mynet:
        ipv4_address: 192.168.168.3
networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.168.0/24