services:
  app:
    image: kmenovschikov/em_test:6.0
    container_name: backend
    networks:
      mynet:
        ipv4_address: 192.168.168.2
  web:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf :/etc/nginx/
    ports:
      - 80:80
    networks:
      mynet:
        ipv4_address: 192.168.168.3
networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.168.0/24